### ISSUE TITLE
Please clarify BSD license

### ISSUE THREAD

**Issue by LocutusOfBorg** [luceneplusplus/LucenePlusPlus#70]
./src/contrib/analyzers/common/analysis/ar/ArabicAnalyzer.cpp
./src/contrib/analyzers/common/analysis/fa/PersianAnalyzer.cpp

In order to have lucene++ in debian I would like to know the LICENSE (they both say BSD) of the two files above, and/or how to generate them at build-time.

thanks

**Comment by alanw** [comment]
These stop-word lists were sourced from: http://members.unine.ch/jacques.savoy/clef/index.html

Arabic: http://members.unine.ch/jacques.savoy/clef/arabicST.txt
Persian: http://members.unine.ch/jacques.savoy/clef/persianST.txt

They are licensed under BSD (from the web page):
All the software/information given out on this Web site is covered by the BSD License (see http://www.opensource.org/licenses/bsd-license.html), with Copyright (c) 2005, Jacques Savoy.

I manually converted these files to utf-8 bytes to be included in the source file (since many (older) compilers complain about non-ascii source files).
